'use strict';

const DocumentStatus = Object.freeze({
  DRAFT: 'DRAFT',
  PROCESSING: 'PROCESSING',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  SUPERSEDED: 'SUPERSEDED',
  INACTIVE: 'INACTIVE',
});

const KnowledgeMode = Object.freeze({
  OPEN_WORLD: 'OPEN_WORLD',
  CLOSED_WORLD: 'CLOSED_WORLD',
});

const DecisionResult = Object.freeze({
  OFFERED: 'OFFERED',
  NOT_OFFERED: 'NOT_OFFERED',
  SUPPORTED: 'SUPPORTED',
  HUMAN_HANDOFF_REQUIRED: 'HUMAN_HANDOFF_REQUIRED',
  INVALID_CONTEXT: 'INVALID_CONTEXT',
});

const IntentType = Object.freeze({
  ENTITY_EXISTENCE: 'ENTITY_EXISTENCE',
  ENTITY_ATTRIBUTE: 'ENTITY_ATTRIBUTE',
});

const DomainErrorCode = Object.freeze({
  INVALID_DOCUMENT_STATUS: 'INVALID_DOCUMENT_STATUS',
  INVALID_DOCUMENT_TRANSITION: 'INVALID_DOCUMENT_TRANSITION',
  INVALID_CROSS_ORG_RELATIONSHIP: 'INVALID_CROSS_ORG_RELATIONSHIP',
  INVALID_SUPERSEDES_RELATIONSHIP: 'INVALID_SUPERSEDES_RELATIONSHIP',
  INVALID_PATIENT_MESSAGE: 'INVALID_PATIENT_MESSAGE',
  MISSING_HANDOFF_TRANSITION_MESSAGE: 'MISSING_HANDOFF_TRANSITION_MESSAGE',
  PUBLICATION_BLOCKED_BY_PROCESSING_FAILURE: 'PUBLICATION_BLOCKED_BY_PROCESSING_FAILURE',
  INCOMPLETE_RETRIEVAL_PROVENANCE: 'INCOMPLETE_RETRIEVAL_PROVENANCE',
  PATIENT_MEMORY_NOT_ALLOWED_IN_DOCUMENT_KNOWLEDGE: 'PATIENT_MEMORY_NOT_ALLOWED_IN_DOCUMENT_KNOWLEDGE',
  GROUNDING_REJECTED: 'GROUNDING_REJECTED',
});

class DomainRuleError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'DomainRuleError';
    this.code = code;
    this.details = details;
  }
}

module.exports = {
  DecisionResult,
  DocumentStatus,
  DomainErrorCode,
  DomainRuleError,
  IntentType,
  KnowledgeMode,
};
